const dutchCities = <String>[
  ''s-Hertogenbosch',
  'Aa en Hunze',
  'Aalsmeer',
  'Aalten',
  'Achtkarspelen',
  'Albrandswaard',
  'Alkmaar',
  'Almere',
  'Alphen aan den Rijn',
  'Alphen-Chaam',
  'Altena',
  'Ameland',
  'Amersfoort',
  'Amstelveen',
  'Amsterdam',
  'Apeldoorn',
  'Arnhem',
  'Assen',
  'Asten',
  'Baarle-Nassau',
  'Baarn',
  'Barendrecht',
  'Barneveld',
  'Beek',
  'Beekdaelen',
  'Beesel',
  'Bergeijk',
  'Bergen',
  'Bergen NH',
  'Bergen op Zoom',
  'Berkelland',
  'Bernheze',
  'Best',
  'Beuningen',
  'Beverwijk',
  'Bilthoven',
  'Bladel',
  'Blaricum',
  'Bloemendaal',
  'Bodegraven-Reeuwijk',
  'Bolsward',
  'Bonaire',
  'Borger-Odoorn',
  'Borsele',
  'Boxtel',
  'Breda',
  'Breukelen',
  'Bronckhorst',
  'Brummen',
  'Brunssum',
  'Bunnik',
  'Buren',
  'Bussum',
  'Capelle aan den IJssel',
  'Castricum',
  'Coevorden',
  'Cranendonck',
  'Culemborg',
  'Dantumadiel',
  'De Bilt',
  'De Fryske Marren',
  'De Ronde Venen',
  'De Wolden',
  'Delft',
  'Den Bosch',
  'Den Haag',
  'Den Helder',
  'Deurne',
  'Deventer',
  'Diemen',
  'Dijk en Waard',
  'Doesburg',
  'Doetinchem',
  'Dongen',
  'Dordrecht',
  'Drachten',
  'Drechterland',
  'Drimmelen',
  'Dronten',
  'Druten',
  'Duiven',
  'Echt-Susteren',
  'Edam-Volendam',
  'Ede',
  'Eemnes',
  'Eemsdelta',
  'Eersel',
  'Eijsden-Margraten',
  'Eindhoven',
  'Elburg',
  'Emmen',
  'Enkhuizen',
  'Enschede',
  'Epe',
  'Ermelo',
  'Etten-Leur',
  'Franekeradeel',
  'Geertruidenberg',
  'Geldermalsen',
  'Geldrop-Mierlo',
  'Geleen',
  'Gemert-Bakel',
  'Gilze en Rijen',
  'Goeree-Overflakkee',
  'Goes',
  'Goirle',
  'Gooise Meren',
  'Gorinchem',
  'Gouda',
  'Groningen',
  'Gulpen',
  'Gulpen-Wittem',
  'Haaren',
  'Haarlem',
  'Haarlemmermeer',
  'Halderberge',
  'Harderwijk',
  'Hardinxveld-Giessendam',
  'Harlingen',
  'Hattem',
  'Heemskerk',
  'Heemstede',
  'Heerde',
  'Heerenveen',
  'Heerhugowaard',
  'Heerlen',
  'Heeze-Leende',
  'Heiloo',
  'Hellevoetsluis',
  'Helmond',
  'Hendrik-Ido-Ambacht',
  'Hengelo',
  'Het Bildt',
  'Het Hogeland',
  'Heusden',
  'Hillegom',
  'Hilvarenbeek',
  'Hilversum',
  'Hoeksche Waard',
  'Hollands Kroon',
  'Hoofddorp',
  'Hoogeveen',
  'Hoogvliet',
  'Hoorn',
  'Horst aan de Maas',
  'Houten',
  'Huizen',
  'Hulst',
  'IJsselstein',
  'Joure',
  'Kaag en Braassem',
  'Kampen',
  'Kapelle',
  'Katwijk',
  'Kerkrade',
  'Koggenland',
  'Kralendijk',
  'Krimpen aan den IJssel',
  'Krimpenerwaard',
  'Laarbeek',
  'Landgraaf',
  'Landsmeer',
  'Langedijk',
  'Lansingerland',
  'Laren',
  'Leeuwarden',
  'Leiden',
  'Leidschendam-Voorburg',
  'Lelystad',
  'Leudal',
  'Leusden',
  'Lingewaard',
  'Lisse',
  'Lochem',
  'Loenen',
  'Loon op Zand',
  'Lopik',
  'Maarssen',
  'Maasdriel',
  'Maasgouw',
  'Maashorst',
  'Maassluis',
  'Maastricht',
  'Medemblik',
  'Meerssen',
  'Meierijstad',
  'Meppel',
  'Middelburg',
  'Midden-Delfland',
  'Midden-Drenthe',
  'Midden-Groningen',
  'Moerdijk',
  'Molenlanden',
  'Montferland',
  'Montfoort',
  'Naarden',
  'Neder-Betuwe',
  'Nederweert',
  'New West',
  'Nieuw-Vennep',
  'Nieuwegein',
  'Nieuwkoop',
  'Nijkerk',
  'Nijmegen',
  'Nissewaard',
  'Noardeast-Fryslân',
  'Noord-Beveland',
  'Noordenveld',
  'Noordoostpolder',
  'Noordwijk',
  'Noordwijkerhout',
  'Nuenen',
  'Nunspeet',
  'Nuth',
  'Oegstgeest',
  'Oirschot',
  'Oisterwijk',
  'Oldambt',
  'Oldebroek',
  'Onderbanken',
  'Online',
  'Oost Gelre',
  'Oosterhout',
  'Ooststellingwerf',
  'Opmeer',
  'Opsterland',
  'Oranjestad',
  'Oss',
  'Ouder-Amstel',
  'Ouderkerk',
  'Oudewater',
  'Overbetuwe',
  'Papendrecht',
  'Peel en Maas',
  'Pekela',
  'Pijnacker-Nootdorp',
  'Poortugaal',
  'Purmerend',
  'Putten',
  'Reimerswaal',
  'Renswoude',
  'Reusel-De Mierden',
  'Rhenen',
  'Rhoon',
  'Ridderkerk',
  'Rijswijk',
  'Roerdalen',
  'Roermond',
  'Roosendaal',
  'Rotterdam',
  'Rucphen',
  'Saba',
  'Schagen',
  'Schiedam',
  'Schiermonnikoog',
  'Schijndel',
  'Schinnen',
  'Schoorl',
  'Schouwen-Duiveland',
  'Simpelveld',
  'Sint Eustatius',
  'Sint-Michielsgestel',
  'Sint-Oedenrode',
  'Sittard',
  'Sittard-Geleen',
  'Sliedrecht',
  'Sluis',
  'Smallingerland',
  'Sneek',
  'Soest',
  'Someren',
  'Son en Breugel',
  'Spijkenisse',
  'Stadskanaal',
  'Stede Broec',
  'Steenbergen',
  'Stein',
  'Stichtse Vecht',
  'Súdwest-Fryslân',
  'Terneuzen',
  'Terschelling',
  'Texel',
  'Teylingen',
  'The Bottom',
  'The Hague',
  'Tholen',
  'Tiel',
  'Tilburg',
  'Tynaarlo',
  'Tytsjerksteradiel',
  'Uden',
  'Uitgeest',
  'Uithoorn',
  'Urk',
  'Utrecht',
  'Utrechtse Heuvelrug',
  'Vaals',
  'Valkenburg aan de Geul',
  'Valkenswaard',
  'Veendam',
  'Veenendaal',
  'Veere',
  'Veghel',
  'Veldhoven',
  'Venlo',
  'Venray',
  'Vlaardingen',
  'Vlieland',
  'Vlissingen',
  'Voerendaal',
  'Voorne aan Zee',
  'Voorschoten',
  'Voorst',
  'Vught',
  'Waadhoeke',
  'Waalre',
  'Waalwijk',
  'Waddinxveen',
  'Wageningen',
  'Wassenaar',
  'Waterland',
  'Weert',
  'Weesp',
  'Werkendam',
  'West Betuwe',
  'West Maas en Waal',
  'Westerkwartier',
  'Westerveld',
  'Westervoort',
  'Westerwolde',
  'Westland',
  'Weststellingwerf',
  'Wijchen',
  'Wijdemeren',
  'Wijk bij Duurstede',
  'Winterswijk',
  'Woensdrecht',
  'Woerden',
  'Wormerland',
  'Woudenberg',
  'Woudrichem',
  'Zaandam',
  'Zaanstad',
  'Zaltbommel',
  'Zandvoort',
  'Zeewolde',
  'Zeist',
  'Zevenaar',
  'Zierikzee',
  'Zoetermeer',
  'Zuidplas',
  'Zundert',
  'Zutphen',
  'Zwijndrecht',
  'Zwolle'
];

List<String> filterCities(String query) {
  final q = query.trim().toLowerCase();
  if (q.isEmpty) return dutchCities.take(40).toList();
  final starts = dutchCities.where((c) => c.toLowerCase().startsWith(q)).toList();
  final contains = dutchCities
      .where((c) => !c.toLowerCase().startsWith(q) && c.toLowerCase().contains(q))
      .toList();
  return [...starts, ...contains];
}
