const dutchCities = <String>[
  "Aa en Hunze",
  "Aalsmeer",
  "Aalten",
  "Achtkarspelen",
  "Alblasserdam",
  "Albrandswaard",
  "Alkmaar",
  "Almelo",
  "Almere",
  "Alphen aan den Rijn",
  "Alphen-Chaam",
  "Altena",
  "Ameland",
  "Amersfoort",
  "Amstelveen",
  "Amsterdam",
  "Apeldoorn",
  "Arnhem",
  "Assen",
  "Asten",
  "Baarle-Nassau",
  "Baarn",
  "Barendrecht",
  "Barneveld",
  "Beek",
  "Beekdaelen",
  "Beesel",
  "Berg en Dal",
  "Bergeijk",
  "Bergen",
  "Bergen NH",
  "Bergen op Zoom",
  "Berkelland",
  "Bernheze",
  "Best",
  "Beuningen",
  "Beverwijk",
  "Bladel",
  "Blaricum",
  "Bloemendaal",
  "Bodegraven-Reeuwijk",
  "Bonaire",
  "Borger-Odoorn",
  "Borsele",
  "Boxtel",
  "Breda",
  "Bronckhorst",
  "Brummen",
  "Brunssum",
  "Bunnik",
  "Buren",
  "Bussum",
  "Capelle aan den IJssel",
  "Castricum",
  "Coevorden",
  "Cranendonck",
  "Culemborg",
  "Dalfsen",
  "Dantumadiel",
  "De Bilt",
  "De Fryske Marren",
  "De Ronde Venen",
  "De Wolden",
  "Delft",
  "Den Bosch",
  "Den Haag",
  "Den Helder",
  "Deurne",
  "Deventer",
  "Diemen",
  "Dijk en Waard",
  "Doesburg",
  "Doetinchem",
  "Dongen",
  "Dordrecht",
  "Drechterland",
  "Drenthe",
  "Drimmelen",
  "Dronten",
  "Druten",
  "Duiven",
  "Echt-Susteren",
  "Edam-Volendam",
  "Ede",
  "Eemnes",
  "Eemsdelta",
  "Eersel",
  "Eijsden-Margraten",
  "Eindhoven",
  "Elburg",
  "Emmen",
  "Enkhuizen",
  "Enschede",
  "Epe",
  "Ermelo",
  "Etten-Leur",
  "Franekeradeel",
  "Geertruidenberg",
  "Geldermalsen",
  "Geldrop-Mierlo",
  "Gemert-Bakel",
  "Gennep",
  "Gilze en Rijen",
  "Goeree-Overflakkee",
  "Goes",
  "Goirle",
  "Gooise Meren",
  "Gorinchem",
  "Gouda",
  "Groningen",
  "Gulpen-Wittem",
  "Haaksbergen",
  "Haarlem",
  "Haarlemmermeer",
  "Halderberge",
  "Hardenberg",
  "Harderwijk",
  "Hardinxveld-Giessendam",
  "Harlingen",
  "Hattem",
  "Heemskerk",
  "Heemstede",
  "Heerde",
  "Heerenveen",
  "Heerhugowaard",
  "Heerlen",
  "Heeze-Leende",
  "Heiloo",
  "Hellendoorn",
  "Hellevoetsluis",
  "Helmond",
  "Hendrik-Ido-Ambacht",
  "Hengelo",
  "Het Bildt",
  "Het Hogeland",
  "Heusden",
  "Hillegom",
  "Hilvarenbeek",
  "Hilversum",
  "Hoeksche Waard",
  "Hollands Kroon",
  "Hoofddorp",
  "Hoogeveen",
  "Hoorn",
  "Horst aan de Maas",
  "Houten",
  "Huizen",
  "Hulst",
  "IJsselstein",
  "Kaag en Braassem",
  "Kampen",
  "Kapelle",
  "Katwijk",
  "Kerkrade",
  "Koggenland",
  "Krimpen aan den IJssel",
  "Krimpenerwaard",
  "Laarbeek",
  "Landgraaf",
  "Landsmeer",
  "Langedijk",
  "Lansingerland",
  "Laren",
  "Leeuwarden",
  "Leiden",
  "Leiderdorp",
  "Leidschendam-Voorburg",
  "Lelystad",
  "Leudal",
  "Leusden",
  "Lingewaard",
  "Lisse",
  "Lochem",
  "Loon op Zand",
  "Lopik",
  "Losser",
  "Maasdriel",
  "Maasgouw",
  "Maashorst",
  "Maassluis",
  "Maastricht",
  "Medemblik",
  "Meerssen",
  "Meierijstad",
  "Meppel",
  "Middelburg",
  "Midden-Delfland",
  "Midden-Drenthe",
  "Midden-Groningen",
  "Moerdijk",
  "Molenlanden",
  "Montferland",
  "Montfoort",
  "Naarden",
  "Neder-Betuwe",
  "Nederweert",
  "Nieuwegein",
  "Nieuwkoop",
  "Nijkerk",
  "Nijmegen",
  "Nissewaard",
  "Noardeast-Fryslân",
  "Noord-Beveland",
  "Noordenveld",
  "Noordoostpolder",
  "Noordwijk",
  "Nuenen",
  "Nunspeet",
  "Nuth",
  "Oegstgeest",
  "Oirschot",
  "Oisterwijk",
  "Oldambt",
  "Oldebroek",
  "Oldenzaal",
  "Onderbanken",
  "Online",
  "Oost Gelre",
  "Oosterhout",
  "Ooststellingwerf",
  "Opmeer",
  "Opsterland",
  "Oss",
  "Ouder-Amstel",
  "Oudewater",
  "Overbetuwe",
  "Papendrecht",
  "Peel en Maas",
  "Pekela",
  "Pijnacker-Nootdorp",
  "Purmerend",
  "Putten",
  "Raalte",
  "Reimerswaal",
  "Renkum",
  "Renswoude",
  "Reusel-De Mierden",
  "Rheden",
  "Rhenen",
  "Ridderkerk",
  "Rijssen-Holten",
  "Rijswijk",
  "Roerdalen",
  "Roermond",
  "Roosendaal",
  "Rotterdam",
  "Rucphen",
  "s-Hertogenbosch",
  "Saba",
  "Schagen",
  "Scherpenzeel",
  "Schiedam",
  "Schiermonnikoog",
  "Schinnen",
  "Schouwen-Duiveland",
  "Simpelveld",
  "Sint Eustatius",
  "Sint-Michielsgestel",
  "Sint-Oedenrode",
  "Sittard",
  "Sittard-Geleen",
  "Sliedrecht",
  "Sluis",
  "Smallingerland",
  "Sneek",
  "Soest",
  "Someren",
  "Son en Breugel",
  "Stadskanaal",
  "Staphorst",
  "Stede Broec",
  "Steenbergen",
  "Steenwijkerland",
  "Stein",
  "Stichtse Vecht",
  "Súdwest-Fryslân",
  "Terneuzen",
  "Terschelling",
  "Texel",
  "Teylingen",
  "The Bottom",
  "The Hague",
  "Tholen",
  "Tiel",
  "Tilburg",
  "Tubbergen",
  "Twenterand",
  "Tynaarlo",
  "Tytsjerksteradiel",
  "Uden",
  "Uitgeest",
  "Uithoorn",
  "Urk",
  "Utrecht",
  "Utrechtse Heuvelrug",
  "Vaals",
  "Valkenburg aan de Geul",
  "Valkenswaard",
  "Veendam",
  "Veenendaal",
  "Veere",
  "Veghel",
  "Veldhoven",
  "Velsen",
  "Venlo",
  "Venray",
  "Vijfheerenlanden",
  "Vlaardingen",
  "Vlieland",
  "Vlissingen",
  "Voerendaal",
  "Voorne aan Zee",
  "Voorschoten",
  "Voorst",
  "Vught",
  "Waadhoeke",
  "Waalre",
  "Waalwijk",
  "Waddinxveen",
  "Wageningen",
  "Wassenaar",
  "Waterland",
  "Weert",
  "West Betuwe",
  "West Maas en Waal",
  "Westerkwartier",
  "Westerveld",
  "Westervoort",
  "Westerwolde",
  "Westland",
  "Weststellingwerf",
  "Westvoorne",
  "Wierden",
  "Wijchen",
  "Wijdemeren",
  "Wijk bij Duurstede",
  "Winterswijk",
  "Woensdrecht",
  "Woerden",
  "Wormerland",
  "Woudenberg",
  "Zaandam",
  "Zaanstad",
  "Zaltbommel",
  "Zandvoort",
  "Zeewolde",
  "Zeist",
  "Zevenaar",
  "Zoetermeer",
  "Zuidplas",
  "Zundert",
  "Zutphen",
  "Zwartewaterland",
  "Zwijndrecht",
  "Zwolle",
];

List<String> filterCities(String query) {
  final q = query.trim().toLowerCase();
  if (q.isEmpty) return dutchCities.take(40).toList();
  final starts = dutchCities
      .where((c) => c.toLowerCase().startsWith(q))
      .toList();
  final contains = dutchCities
      .where(
        (c) => !c.toLowerCase().startsWith(q) && c.toLowerCase().contains(q),
      )
      .toList();
  return [...starts, ...contains];
}
