const dutchCities = <String>[
  'Amsterdam',
  'Rotterdam',
  'Den Haag',
  'The Hague',
  'Utrecht',
  'Eindhoven',
  'Groningen',
  'Almere',
  'Tilburg',
  'Breda',
  'Nijmegen',
  'Arnhem',
  'Apeldoorn',
  'Haarlem',
  'Haarlemmermeer',
  'Hoofddorp',
  'Zaanstad',
  'Zaandam',
  'Amersfoort',
  'Enschede',
  "'s-Hertogenbosch",
  'Den Bosch',
  'Zwolle',
  'Zoetermeer',
  'Leiden',
  'Leeuwarden',
  'Ede',
  'Maastricht',
  'Dordrecht',
  'Westland',
  'Alphen aan den Rijn',
  'Alkmaar',
  'Delft',
  'Emmen',
  'Deventer',
  'Venlo',
  'Helmond',
  'Hilversum',
  'Amstelveen',
  'Heerlen',
  'Purmerend',
  'Hengelo',
  'Schiedam',
  'Spijkenisse',
  'Nissewaard',
  'Roosendaal',
  'Oss',
  'Schiedam',
  'Vlaardingen',
  'Gouda',
  'Lelystad',
  'Almelo',
  'Spijkenisse',
  'Capelle aan den IJssel',
  'Veenendaal',
  'Katwijk',
  'Zeist',
  'Nieuwegein',
  'Barneveld',
  'Assen',
  'Middelburg',
  'Vlissingen',
  'Terneuzen',
  'Goes',
  'Bergen op Zoom',
  'Roermond',
  'Sittard',
  'Geleen',
  'Weert',
  'Venray',
  'Doetinchem',
  'Zutphen',
  'Harderwijk',
  'Epe',
  'Wageningen',
  'Tiel',
  'Culemborg',
  'Houten',
  'IJsselstein',
  'Woerden',
  'Soest',
  'Baarn',
  'Hilversum',
  'Bussum',
  'Naarden',
  'Huizen',
  'Blaricum',
  'Laren',
  'Weesp',
  'Diemen',
  'Ouder-Amstel',
  'Uithoorn',
  'Aalsmeer',
  'Nieuw-Vennep',
  'Badhoevedorp',
  'Heemstede',
  'Bloemendaal',
  'Zandvoort',
  'Beverwijk',
  'Heemskerk',
  'Castricum',
  'Heiloo',
  'Bergen',
  'Schagen',
  'Den Helder',
  'Hoorn',
  'Enkhuizen',
  'Medemblik',
  'Purmerend',
  'Volendam',
  'Edam',
  'Wormerveer',
  'Koog aan de Zaan',
  'Landsmeer',
  'Oostzaan',
  'Waterland',
  'Leiden',
  'Leiderdorp',
  'Oegstgeest',
  'Voorschoten',
  'Wassenaar',
  'Rijswijk',
  'Voorburg',
  'Leidschendam',
  'Zoetermeer',
  'Pijnacker',
  'Nootdorp',
  'Delft',
  'Schiedam',
  'Vlaardingen',
  'Maassluis',
  'Spijkenisse',
  'Hellevoetsluis',
  'Brielle',
  'Goeree-Overflakkee',
  'Dordrecht',
  'Zwijndrecht',
  'Papendrecht',
  'Sliedrecht',
  'Gorinchem',
  'Hardinxveld-Giessendam',
  'Alblasserdam',
  'Hendrik-Ido-Ambacht',
  'Barendrecht',
  'Ridderkerk',
  'Krimpen aan den IJssel',
  'Capelle aan den IJssel',
  'Rotterdam',
  'Schiedam',
  'Hoek van Holland',
  'Ede',
  'Wageningen',
  'Renkum',
  'Oosterbeek',
  'Velp',
  'Rozendaal',
  'Doesburg',
  'Dieren',
  'Brummen',
  'Voorst',
  'Lochem',
  'Berkelland',
  'Winterswijk',
  'Aalten',
  'Doetinchem',
  'Montferland',
  'Zevenaar',
  'Duiven',
  'Westervoort',
  'Overbetuwe',
  'Lingewaard',
  'Nijmegen',
  'Wijchen',
  'Beuningen',
  'Druten',
  'West Maas en Waal',
  'Heumen',
  'Mook en Middelaar',
  'Gennep',
  'Bergen Limburg',
  'Venlo',
  'Venray',
  'Horst aan de Maas',
  'Peel en Maas',
  'Nederweert',
  'Weert',
  'Roermond',
  'Echt-Susteren',
  'Sittard-Geleen',
  'Beek',
  'Stein',
  'Meerssen',
  'Valkenburg aan de Geul',
  'Gulpen-Wittem',
  'Vaals',
  'Kerkrade',
  'Landgraaf',
  'Brunssum',
  'Heerlen',
  'Maastricht',
  'Eijsden-Margraten',
  'Gulpen',
  'Breda',
  'Oosterhout',
  'Etten-Leur',
  'Roosendaal',
  'Bergen op Zoom',
  'Steenbergen',
  'Woensdrecht',
  'Halderberge',
  'Moerdijk',
  'Drimmelen',
  'Geertruidenberg',
  'Oosterhout',
  'Dongen',
  'Gilze en Rijen',
  'Goirle',
  'Tilburg',
  'Oisterwijk',
  'Hilvarenbeek',
  'Goirle',
  'Waalwijk',
  'Heusden',
  'Vught',
  'Sint-Michielsgestel',
  "'s-Hertogenbosch",
  'Oss',
  'Uden',
  'Veghel',
  'Meierijstad',
  'Schijndel',
  'Sint-Oedenrode',
  'Boxtel',
  'Best',
  'Son en Breugel',
  'Eindhoven',
  'Veldhoven',
  'Waalre',
  'Valkenswaard',
  'Bergeijk',
  'Eersel',
  'Bladel',
  'Reusel-De Mierden',
  'Oirschot',
  'Best',
  'Helmond',
  'Geldrop-Mierlo',
  'Nuenen',
  'Gemert-Bakel',
  'Laarbeek',
  'Deurne',
  'Asten',
  'Someren',
  'Cranendonck',
  'Heeze-Leende',
  'Valkenswaard',
  'Groningen',
  'Haren',
  'Ten Boer',
  'Hoogezand-Sappemeer',
  'Veendam',
  'Stadskanaal',
  'Winschoten',
  'Oldambt',
  'Delfzijl',
  'Appingedam',
  'Eemsdelta',
  'Het Hogeland',
  'Westerkwartier',
  'Midden-Groningen',
  'Pekela',
  'Westerwolde',
  'Assen',
  'Emmen',
  'Hoogeveen',
  'Meppel',
  'Coevorden',
  'Borger-Odoorn',
  'Aa en Hunze',
  'Tynaarlo',
  'Noordenveld',
  'Westerveld',
  'De Wolden',
  'Midden-Drenthe',
  'Leeuwarden',
  'Sneek',
  'Sudwest-Fryslan',
  'Heerenveen',
  'Drachten',
  'Smallingerland',
  'Dokkum',
  'Noardeast-Fryslan',
  'Dantumadiel',
  'Tytsjerksteradiel',
  'Achtkarspelen',
  'Opsterland',
  'Ooststellingwerf',
  'Weststellingwerf',
  'Waadhoeke',
  'Harlingen',
  'Franeker',
  'Vlieland',
  'Terschelling',
  'Ameland',
  'Schiermonnikoog',
  'Enschede',
  'Hengelo',
  'Almelo',
  'Oldenzaal',
  'Losser',
  'Dinkelland',
  'Tubbergen',
  'Twenterand',
  'Wierden',
  'Rijssen-Holten',
  'Hellendoorn',
  'Raalte',
  'Olst-Wijhe',
  'Deventer',
  'Voorst',
  'Zutphen',
  'Lochem',
  'Berkelland',
  'Winterswijk',
  'Haaksbergen',
  'Hof van Twente',
  'Borne',
  'Zwolle',
  'Kampen',
  'Hattem',
  'Heerde',
  'Epe',
  'Oldebroek',
  'Elburg',
  'Nunspeet',
  'Harderwijk',
  'Ermelo',
  'Putten',
  'Nijkerk',
  'Barneveld',
  'Scherpenzeel',
  'Renswoude',
  'Veenendaal',
  'Rhenen',
  'Wageningen',
  'Almere',
  'Lelystad',
  'Dronten',
  'Zeewolde',
  'Urk',
  'Noordoostpolder',
  'Emmeloord',
];

const otherCities = <String>[
  'Antwerp',
  'Ghent',
  'Brussels',
  'Brugge',
  'Leuven',
  'Berlin',
  'Hamburg',
  'Munich',
  'Cologne',
  'Dusseldorf',
  'Paris',
  'Lyon',
  'London',
  'Manchester',
  'Birmingham',
  'Madrid',
  'Barcelona',
  'Rome',
  'Milan',
  'Vienna',
  'Zurich',
  'Geneva',
  'Copenhagen',
  'Stockholm',
  'Oslo',
  'Helsinki',
  'Dublin',
  'Lisbon',
  'Prague',
  'Warsaw',
  'New York',
  'Los Angeles',
  'Toronto',
  'Vancouver',
  'Dubai',
  'Istanbul',
  'Tehran',
];

List<String> allCities() {
  final seen = <String>{};
  final list = <String>[];
  for (final city in [...dutchCities, ...otherCities]) {
    final key = city.toLowerCase();
    if (seen.add(key)) list.add(city);
  }
  list.sort();
  return list;
}

List<String> filterCities(String query) {
  final q = query.trim().toLowerCase();
  final all = allCities();
  if (q.isEmpty) return all.take(12).toList();
  final starts = all.where((city) => city.toLowerCase().startsWith(q)).toList();
  final contains = all
      .where(
        (city) =>
            !city.toLowerCase().startsWith(q) && city.toLowerCase().contains(q),
      )
      .toList();
  return [...starts, ...contains].take(12).toList();
}
