const allowedSkills = <String>[
  'Languages',
  'Teaching and tutoring',
  'Study support',
  'Reading and writing',
  'Translation',
  'Public speaking',
  'Computers and internet',
  'Programming',
  'Website and apps',
  'Design and graphics',
  'Photography',
  'Video and audio',
  'Music',
  'Art and crafts',
  'Cooking and baking',
  'Food and nutrition',
  'Health and wellbeing',
  'Fitness and movement',
  'Mindfulness',
  'Child support',
  'Senior support',
  'Home organisation',
  'Cleaning and household',
  'Gardening',
  'Repairs and making',
  'Clothing and sewing',
  'Beauty and grooming',
  'Driving support',
  'Errands and local help',
  'Administration',
  'Job search help',
  'CV and applications',
  'Business basics',
  'Money basics',
  'Marketing and social media',
  'Events and hosting',
  'Sports and games',
  'Pets and animals',
  'Travel and culture',
  'Community support',
];